[package]
name = "rusty_game-jam-2021-ggez"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.6.0"
serde = "1.0"
# serde_derive = "1.0"
serde_json = "1.0"